modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/PufferTeam/Grassy-Plants/issues"

[[mods]]
modId="grassyplants"
version="${file.jarVersion}"
displayName="Grassy Plants"
logoFile="examplemod.png"
credits="TurtyWurty, minemobs"
authors="FuguTeam"
description='''
...
'''
